package io.github.zeroone3010.turtleviewer.lexer

/** Lexical categories used by the Turtle editor and viewer. */
enum class TurtleTokenType {
    WHITESPACE, COMMENT,
    PREFIX_DIRECTIVE, BASE_DIRECTIVE, SPARQL_PREFIX, SPARQL_BASE,
    IRI, PREFIX_NAME, BLANK_NODE_LABEL,
    STRING, LONG_STRING,
    INTEGER, DECIMAL, DOUBLE, BOOLEAN, KEYWORD_A,
    LANGUAGE_TAG, DATATYPE_MARKER,
    SEMICOLON, COMMA, DOT,
    OPEN_BRACKET, CLOSE_BRACKET, OPEN_PAREN, CLOSE_PAREN, OPEN_BRACE, CLOSE_BRACE,
    DOUBLE_CARET,
    ERROR, EOF
}
